## **Ejercicio 1: Operaciones sin bucles**

Tienes un arreglo de NumPy que representa precios precios = np.array([100, 102, 105, 101]). 

Sin usar ningún bucle, suma 5 a todos los precios y luego multiplícalos por 2.

In [1]:
import numpy as np

In [3]:
arreglo = np.array([100,102,105,101])

In [6]:
(arreglo + 5) * 2

array([210, 214, 220, 212])

**Ejercicio 2: Retornos logarítmicos vectorizados**

El problema: Toma el arreglo de precios del Ejercicio 1. Calcula los retornos logarítmicos continuos para esos precios.

In [13]:
log_returns = np.log(arreglo[1:] / arreglo[:-1])

In [14]:
log_returns

array([ 0.01980263,  0.02898754, -0.03883983])

In [11]:
arreglo[1:]

array([102, 105, 101])

In [15]:
arreglo[:-1]

array([100, 102, 105])